version: '3'

services:

  masakhane:
    build: .
    ports:
      - '5000:5000'
    depends_on:
     - postgres
    container_name: masakhane
    env_file: # Pass the environment variables in the .env file to the container
      - .env
    # networks:
    #   - backend

  postgres:
    image: "postgres:11-alpine"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
     - "5435:5432"
    volumes:
     - 'postgres:/usr/share/postgresql/data'


volumes:
 postgres:
    driver: local